sqlplus / as sysdba;

sqlplus system/Manager1

alter session set "_ORACLE_SCRIPT"=true;

CREATE TABLESPACE EMPLEADOS
	DATAFILE 'C:\Datos\empleados01.dbf' SIZE 250M
	AUTOEXTEND ON NEXT 1M MAXSIZE 300M
	EXTENT MANAGEMENT LOCAL UNIFORM SIZE 200K
	SEGMENT SPACE MANAGEMENT AUTO;
    
CREATE TABLESPACE EMPLEADOS2
	DATAFILE '/u01/ordata/bdEmpleados/dat/empleados02.dbf' SIZE 250M
	AUTOEXTEND ON NEXT 1M MAXSIZE 300M
	EXTENT MANAGEMENT LOCAL UNIFORM SIZE 200K
	SEGMENT SPACE MANAGEMENT AUTO;
